name: 'Nexus Tarraform'
description: 'Request nexus to trigger TF'
inputs:
  credentials:
    description: 'Credentials for nexus'
    required: true
  environment:
    description: 'The environment to Terraform'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/tf_nexus.sh
      shell: bash
      env:
        NX_CRED: ${{ inputs.credenials }}
        TF_DIR: ${{ inputs.environment }} 
