name: 'Deept Auto Deploy'
description: 'Request nexus to trigger DAP'
inputs:
  credentials:
    description: 'Credentials for nexus'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/deept_auto_deploy.sh
      shell: bash
      env:
        NX_CRED: ${{ inputs.credenials }}