name: 'Update Master File and Open PR'
description: 'Fetches the requirements-master, commits, and creates a PR'
inputs:
  target-master-file-url:
    description: 'URL of the master requirements file to fetch'
    required: false
    default: 'https://raw.githubusercontent.com/PangeaResearch/pangea-ppm/main/requirements-master.txt'
  target-ppm-file-url:
    description: 'URL of the ppm utils file to fetch'
    required: false
    default: 'https://raw.githubusercontent.com/PangeaResearch/pangea-ppm/main/ppm_utils.py'
  commit-message:
    description: 'Commit message'
    required: false
    default: 'Update requirements-master.txt'
  branch-name:
    description: 'Branch name for the new branch'
    required: false
    default: 'update-requirements-master'
  pr-title:
    description: 'Title for the PR'
    required: false
    default: 'Update requirements-master.txt'
  pr-body:
    description: 'Body for the PR'
    required: false
    default: 'Update requirements-master.txt'

runs:
  using: 'composite'    
  steps:
  - name: Fetch requirements-master file
    shell: bash
    run: |
      curl -sL -H "Authorization: token ${{ env.PPM_TOKEN }}" ${{ inputs.target-master-file-url }} > requirements-master.txt
      curl -sL -H "Authorization: token ${{ env.PPM_TOKEN }}" ${{ inputs.target-ppm-file-url }} > ppm_utils.py
  - name: Create Pull Request
    uses: PangeaResearch/create-pull-request@main
    with:
      commit-message: ${{ inputs.commit-message }}
      title: ${{ inputs.pr-title }}
      body: ${{ inputs.pr-body }}
      base: main
      branch: ${{ inputs.branch-name }}
      delete-branch: true
