name: 'Deeppt Preproc Auto Deploy'
description: 'Request nexus to trigger DAP'
inputs:
  credentials:
    description: 'Credentials for nexus'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/deeppt-preproc-auto-deploy.sh
      shell: bash
      env:
        NX_CRED: ${{ inputs.credentials }}
