name: 'Portal Stage Autodeploy'
description: 'Request nexus to trigger PSA'
inputs:
  credentials:
    description: 'Credentials for nexus'
    required: true
  version:
    description: 'Version number to Deploy'
    required: true
  group:
    description: 'Group Name'
    required: true
  suffix:
    description: 'Suffix of file (Ex: gz, tgz, tar, zip)'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/portal_stage_autodeploy.sh "${{ inputs.group }}" "${{ inputs.version }}" "${{ inputs.suffix }}"
      shell: bash
      env:
        NX_CRED: ${{ inputs.credentials }}
