name: 'ECR Auto Deploy'
description: 'Request nexus to trigger DAP'
inputs:
  credentials:
    description: 'Credentials for nexus'
    required: true
  image:
    description: 'name of image to pull'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/ecr_auto_deploy.sh
      shell: bash
      env:
        NX_CRED: ${{ inputs.credenials }}
        IMG_NAME: ${{ inputs.image }}