name: 'ECR Auto Deploy'
description: 'Request nexus to trigger DAP'
inputs:
  credentials:
    description: 'Credentials for nexus'
    required: true
  images:
    description: 'names of images to pull'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/ecr_auto_deploy.sh ${{ inputs.images }}
      shell: bash
      env:
        NX_CRED: ${{ inputs.credentials }}
